---
apiVersion: v1
kind: Namespace
metadata:
  name: snens
  labels:
    mesh: sneappmesh
    gateway: ingress-gw-new
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: sneappmesh
spec:
  namespaceSelector:
    matchLabels:
      mesh: sneappmesh
  egressFilter:
    type: ALLOW_ALL