apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: sne-app
  namespace: snens
spec:
  podSelector:
    matchLabels:
      app: sne-app
  listeners:
    - portMapping:
        port: 8080
        protocol: http
      healthCheck:
        protocol: http
        path: '/entitlementsearch/sample'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  serviceDiscovery:
    dns:
      hostname: sne-app-svc.snens.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: sne-app-svc
  namespace: snens
spec:
  awsName: sne-app-svc.snens.svc.cluster.local
  provider:
    virtualRouter:
        virtualRouterRef:
            name: sne-app-svc-router     
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: snens
  name: sne-app-svc-router
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: route-to-sne-app
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef: 
                name: sne-app
              weight: 1
        retryPolicy:
            maxRetries: 2
            perRetryTimeout:
                unit: ms
                value: 2000
            httpRetryEvents:
                - server-error
                - client-error
                - gateway-error




