apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev

resources:
  #- 1_meshcreate.yml
  #- 2_appmesh_components.yml
  #- 3_sne_secret
  - 4_javatest-app-deployment-all.yml
 # - 4_sne-app-virtualgw.yml
 # - 5_sne-ingress.yml
